### ISSUE TITLE
When user tries to edit the 'Contents', it is showing as html code

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#10]
1. Login as Trainer
2. Click on My Course -> click on course details 
3. Click on Contents
4. Click on Edit icon

Notice that when user edits the Contents it is showing in html code.

![image](https://user-images.githubusercontent.com/37771328/37947164-28986a94-31a7-11e8-9f50-9933145dd021.png)

**Comment by samurailens** [comment]
Fixed and Pushed.

**Appears in Build : APR 2, 2018**
