### ISSUE TITLE
Batches - When user tries to edit the Batch details, previous details are not populating.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#11]
1. Login as Trainer
2. Click on Dashboard
3. Click on Courses -> Click on Batches -> Batches tab
4. Click on Update Batch info

Notice that Start Date and End Date are not populating in fields.

Expected Result: It would be good if previous details populates in Start Date and End Date, like remaining fields.

![image](https://user-images.githubusercontent.com/37771328/37947375-5bffb4b8-31a8-11e8-96ec-ac6c7528cecc.png)

**Comment by gangwork** [comment]
fixed will be appearing in todays build
