### ISSUE TITLE
Enrolled Courses are not displaying for Students

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#116]
1. Login as Trainer
2. Create Course and Batch
3. Add one student to the batch
4. Navigate to Students tab and select that student, click on arrow mark

Notice that all enrolled courses are not displaying for students.

![image](https://user-images.githubusercontent.com/37771328/39969257-c31cb222-56f6-11e8-96a4-3765c485c299.png)

**Comment by phani434** [comment]
@NareshTeed This issue is fixed.
All courses are now listed clearly using batch information.
Assigning back to you, please close it if it is working as per the requirement.

Thanks,
Phani
