### ISSUE TITLE
Update and Cancel buttons are showing twice in particular scenario.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#12]
1. Login as Trainer
2. Click on My courses -> click on Create Batch
3. Click on Create Batch tab -> click on edit icon which is beside the course name
![image](https://user-images.githubusercontent.com/37771328/37957425-865485b8-31cb-11e8-8387-a1a9165f93f8.png)
Notice that when user clicks on Edit button, Cancel and Update buttons are displaying. Please check the above screenshot.
4. Click on Update Batch info

Issue – Cancel and update buttons are displaying twice.

![image](https://user-images.githubusercontent.com/37771328/37957518-c7a1eee8-31cb-11e8-8dea-981f71decb82.png)

**Comment by gangwork** [comment]
fixed will be appearing in todays build
