### ISSUE TITLE
Without entering any data When user clicks on Search icon it is navigating to empty page

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#122]
1. Launch the Teedknow.com
2. Click on Search icon.

Notice that it is navigating to empty page.
![image](https://user-images.githubusercontent.com/37771328/40271163-07dffd6e-5bb7-11e8-8171-8c60f21861b1.png)

Expected Result: If user clicks on Search icon without entering data, it should remain in same screen.
- If user enter any valid data and clicks on Search icon then it should navigate to other screen and should  display the results.

**Comment by phani434** [comment]
@NareshTeed Can you please revert back if you see this issue, this got fixed by @GANG7
