### ISSUE TITLE
When user clicks on Remove button, application is not throwing any alert message.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#123]
1. Login as Trainer
2. Navigate to Course / Program and select course, click on Remove button

Notice that when user clicks on Remove button, application is not throwing any alert message.

Expected Result: When user clicks on Remove button, application should throw an alert message with Yes or No options. If user clicks on Yes button then it should remove the course/ program. If user clicks on No button then it should remain same.

**Comment by phani434** [comment]
Hello Gangadhar, 



Please take a look into the issue. 



Thanks,

Phani 





---- On Sat, 19 May 2018 12:55:46 -0500 NareshTeed &lt;notifications@github.com&gt; wrote ----




Assigned #123 to @phani434.

**Comment by phani434** [comment]
@NareshTeed Can you please ask your team to take a look at the issue and let us know if you still see the issue. 

Thanks,
Phani

**Comment by NareshTeed** [comment]
Working fine. Hence closing the bug,
