### ISSUE TITLE
Add Student - Without entering mandatory fields, user is able to add students to the batch.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#13]
1. Login as Trainer
2. Click on Dashboard -> Click on My courses ->Click on course details
3. Click on Batch tab ->Click on 'Add Candidate to this Batch'
4. Select Batch
5. In Add student tab ->Dn't enter any values, click on 'Add student' button

Notice that when user clicks on 'Add student' button, automatically candidate is adding to the batch as guest.

Expected Result: If user doesn't enter any mandatory fields, then application should not allow(adding the student) the candidate to the batch.

![image](https://user-images.githubusercontent.com/37771328/37959705-57de3142-31d1-11e8-93b4-be26d1885d1c.png)

**Comment by gangwork** [comment]
fixed will be appearing in todays build
