### ISSUE TITLE
There is no back button in "Update batch info" screen.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#14]
1. Login as Trainer
2. Click on Dashboard ->Click on My courses ->click on Course details
3. Click on Batch tab ->click on View candidate list / Add Candidate to this Batch
4. Select batch 
![image](https://user-images.githubusercontent.com/37771328/37961477-0a15f40e-31d6-11e8-97c5-210a387e3acb.png)

It would be good if we have back button in this screen like Dashboard. Check the below screenshot:
![image](https://user-images.githubusercontent.com/37771328/37961508-1c93f176-31d6-11e8-95c2-726437ba35dd.png)

**Comment by samurailens** [comment]
Fixed and Pushed.

Appears in Build : APR 2, 2018
