### ISSUE TITLE
Lead - No validations checks for fields in Lead screen

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#15]
1. Login as Trainer
2. Click on Dashboard -> click on Lead 
3.  Enter text in 'Pick a course' field
Issue -  User should not have permission to enter any text because that is non editable field
4. Enter alphabets in phone number
Issue - It should allow only Numbers not alphabets
5. Enter all invalid data and click on Save button
Issue - Application is showing a notification that lead has been created successfully. 
Expected result: It should not allow until user enters valid details in fields like phone number and selecting correct course in Pick a course field.

![image](https://user-images.githubusercontent.com/37771328/37983859-443af7b0-3212-11e8-81f3-18465b5f0cda.png)

**Comment by gangwork** [comment]
fixed will be appearing in todays build
