### ISSUE TITLE
In Login page, when user hover on 'Create a new Account' and 'Forgot Password' mouse pointer is not changing to hand icon

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#16]
In Login page, when user hover on 'Create a new Account' and 'Forgot Password' mouse pointer is not changing to hand icon.

![image](https://user-images.githubusercontent.com/37771328/38042939-56717d16-32d3-11e8-9542-fcac3dd45c86.png)

Click on 'Create a new Account'  after navigating to create new account screen, hover on Have Account?Login Here. Here also hand icon should be displayed.

![image](https://user-images.githubusercontent.com/37771328/38043230-2b0cf8ca-32d4-11e8-9a3d-d3070ae255fb.png)

**Comment by gangwork** [comment]
fixed will be appearing in todays build

**Comment by NareshTeed** [comment]
Today I have retested the bug, still I am able to replicate the issue. Can you look into this issue again.
