### ISSUE TITLE
Developer info is seen, when user clicks on Teedknow.com in modal window of google account,

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#18]
1. Enter Teedknow.com in address bar 
2. Click on My Account 
3. Click on Continue with Google
4. In Google account modal window
5. Click on teedknow,com

One popup window is displayed, check the below screenshot, **Is this expected behavior??**
![image](https://user-images.githubusercontent.com/37771328/38165000-c19808a4-352a-11e8-8f39-92c4273a2aec.png)

**Comment by samurailens** [comment]
The Developer information cannot be hidden.  We use Google for authentication, and the associated domain and developer email shall be shown just to show that this Application is authorized by Google and is a verified account.

Only Google in-house products like Youtube can hide this information.  This is primarily meant for users to know that everything is under scrutiny.

**Comment by samurailens** [comment]
Closing issue as this is expected behavior, for non-Google products.
