### ISSUE TITLE
Chat window - Courser point is missing, after pressing Enter keyword in keyboard/ send in chat window.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#20]
1. Login as Trainer
2. Click on any chat window.
3. Enter text and press Enter keyword from keyboard
4.  Without moving your courser point try to enter text 

Notice that when user clicks on send in chat window or press enter keyword in keyboard, then courser point is missing. Again user need to place his cursor in that chat window.
Please check the screenshot below:
![image](https://user-images.githubusercontent.com/37771328/38165357-a717e5da-352f-11e8-9e9f-5a54fe101b3a.png)

Expected Result: When user clicks on Send or press enter keyword, cursor point should be in same place, so that user can enter message.

For reference please check the facebook chat window.

**Comment by rajesh7777** [comment]
Hi sachin,

As discussed on Monday, can we have call every alternate two days for half
an hour, so that everybody are on same page.

Please let me know ur convenient timings.

Regards,
Rajesh.

**Comment by NareshTeed** [comment]
Retested the issue and working fine. Hence changing the status to Closed.

Build no - 0.1.8
