### ISSUE TITLE
Chat window - Unable to close the chat window by clicking on 'X' symbol.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#21]
1. Login as Trainer
2. Click on any chat window.
3. Enter text and press 'Enter' keyword from keyboard
4. Click on X symbol which is available in chat window

Issue - User is unable to close the chat window by clicking on X symbol. Please see the below screenshot:

![image](https://user-images.githubusercontent.com/37771328/38165470-675f1894-3531-11e8-84fe-3fd915cb2343.png)

Expected Result: When user clicks on X symbol, chat window should close.

**Comment by samurailens** [comment]
Fixed and Pushed.

**Appears in Build : APR 2, 2018**
