### ISSUE TITLE
Chat Window - When user clicks on send button, vertical scrollbar is moving top.  

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#22]
1. Login as Trainer
2. Click on Chat window
3. Enter messages till scroll bar appears
4. Enter text and click on send / enter keyword

Issue - When user clicks on send / enter keyword, scroll bar is moving to top. 

Expected Result: When user clicks on send/ enter keyword, scroll bar should not move to top, so that user can read recent messages. Please see the screenshot below:

![image](https://user-images.githubusercontent.com/37771328/38165707-41594c4c-3535-11e8-9de3-5297e0c8d052.png)

**Comment by samurailens** [comment]
Fixed and Pushed.

**Appears in Build : APR 2, 2018**
