### ISSUE TITLE
After logged out from application still chat window is displaying.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#24]
Please see the below screenshot:
![image](https://user-images.githubusercontent.com/37771328/38166040-ac701bf0-353a-11e8-9b55-13da81ce72b9.png)

Expected Result: When user sign out from application, no chat windows should be displayed.

**Comment by samurailens** [comment]
Fixed and Pushed.

**Appears in Build : APR 2, 2018**
