### ISSUE TITLE
Spelling mistakes

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#25]
1. Login as Trainer
2. Click on My courses -> click on course content
check the screenshot
![image](https://user-images.githubusercontent.com/37771328/38166227-f033819e-353d-11e8-812e-616a53b2e722.png)
![image](https://user-images.githubusercontent.com/37771328/38166233-053989d0-353e-11e8-9dfe-8ad41c1fc37b.png)
3.

**Comment by samurailens** [comment]
Corrected and fixed. 

Will appear in today's build.

**Build Date : APR 02, 2018.**
