### ISSUE TITLE
Assignments - Button label is wrong in Assignments tab.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#26]
1. Login as Trainer
2. Click on Dashboard
3. Click on My Courses -> Click on Assignment

Issue - Button label is wrong. Instead of "New Assignment" it is showing as "New Batch"
please see the screenshot below:
![image](https://user-images.githubusercontent.com/37771328/38166506-5d1ce986-3542-11e8-8cea-197ec974edac.png)

**Comment by samurailens** [comment]
Corrected Label.

Fixed and Pushed.

Appears in Build : APR 2, 2018
