### ISSUE TITLE
Assignments - Without entering mandatory fields user is able to create new assignments.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#28]
1. Login as Trainer
2. Click on My courses
3. Click on Course content 
4. Click on Assignments tab
5. Click on New button 
6. without entering any values click on Save button

Issue: Notice that user is able to create assignments without entering any mandatory fields. Please see the below screenshot.

![image](https://user-images.githubusercontent.com/37771328/38166651-fd1d8056-3544-11e8-99ac-a403602edf7a.png)

Expected Result: 

If user tries to save without entering mandatory fields then application should not allow the user to save the new Assignment.

**Comment by samurailens** [comment]
Fixed and pushed. 

Changes shall be seen in **Build : APR 02 2018**
