### ISSUE TITLE
Assignments - Existing Assignments details are displayed, When user tries to create new assignment.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#29]
1. Login as Trainer
2. Click on My courses
3. Click on Course content 
4. Click on Assignments tab
5. Make sure already some Assignments are available in Grid with attachments
6. Click on New 

Issue - Notice that existing Assignments details are populating and even attachments are displaying.

Expected Result: Existing assignment details should not display when user clicks on New assignment. 

![image](https://user-images.githubusercontent.com/37771328/38166940-2f93619a-354a-11e8-83a7-da1475154cd3.png)

**Comment by samurailens** [comment]
Fixed and Pushed.

**Appears in Build : APR 2, 2018**
