### ISSUE TITLE
Unable to create new account in My Account tab.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#30]
1. Launch the application 
2. Click on My Account
3. Click on Create a new account
4. Enter all valid details 
5. Click on Create Account. 

Issue - Just notification is displaying as Registering but unable to create new user.

![image](https://user-images.githubusercontent.com/37771328/38167083-1305d514-354d-11e8-8f05-11f273abdbcc.png)

**Comment by samurailens** [comment]
Might have tested during server downtime. It works as expected in the current build on Teedknow.com

Will keep everyone informed during next downtime.
