### ISSUE TITLE
[Programmes - Batches] - 404 error is seen when user clicks on 'View Candidate List'/Add Candidate to this Batch'/ 'Update Batch Info'

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#33]
Multiple issues for Programs:

1. Login as Trainer
2. Click on 'My Programs
3. Try to click on Existing program
**Issue** - Notice that when user clicks on existing program it is not navigating to Detail tab.
For reference please check the My courses.
4. Select any existing program and click on New Batch.
5. Click on Edit icon and update the fields, Click on Update button
**Issue** - 
Notice that when user clicks on update button nothing happens.
6. Navigate to back and again click on New batch
Create New batch, after successful creation of batch. Click on' View Candidate List'/'Add Candidate to this Batch' and 'Update Batch info'

**Issue** 404 error is seen, when user clicks on 'View Candidate List'/'Add Candidate to this Batch'/'Update Batch info', 
![image](https://user-images.githubusercontent.com/37771328/38175466-6c172d3a-35fa-11e8-9df0-b2f378d94e2f.png)

**Comment by samurailens** [comment]
@gangwork  : Links are broken. Please take it up.

**Comment by gvsphani** [comment]
![image](https://user-images.githubusercontent.com/19274860/38844351-a5ecf1ba-41b8-11e8-93fa-dfbf003629f6.png)
It is working as expected. 

Thanks,
Phani

**Comment by gvsphani** [comment]
Issue fixed in build v0.1.6

**Comment by NareshTeed** [comment]
Retested the issue and working fine. Hence changing the status to Closed.

Build no - 0.1.8
