### ISSUE TITLE
Course - User is unable to enter points wise in 'Key Takeaways' field. 

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#35]
1. Login as a Trainer
2. Click on My Courses
3. Click on Create course
4. Try to enter point by point in Takeaways field
Example - 1. Get full access
                 2. Get access to application

Issue - User is unable to enter points wise in Takeaways field.

![image](https://user-images.githubusercontent.com/37771328/38184448-6d5f7bb4-3665-11e8-9788-7d9ebbadc9a3.png)

**Comment by samurailens** [comment]
Key Takeaways are another alternative for short description. This is not supposed to contain **RICH TEXT** editing like **Contents**. 

The content in Key Takeaways shall be plain text format for multi-purpose. No changes required for closure.
