### ISSUE TITLE
For every screen there should be back button in place of Dashboard.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#37]
1. Login as Trainer
2. Click on My Courses
3. Click on New Course
4. Click on <- Dashboard
![image](https://user-images.githubusercontent.com/37771328/38184930-dc891628-3668-11e8-962a-d419dba63c53.png)
Issue - Instead of navigating to Dashboard, it would be good if user navigates to previous screen.
- If user wants to navigate to Dashboard directly he/she can click on Dashboard.
- This issue is applicable to all screens.

**Comment by samurailens** [comment]
@gangwork, @kranthi91: please check and cross verify if we have 'back' button for each component. Let's close this if everything is in place.
