### ISSUE TITLE
Organizer - Gmail profile image is displayed very large in Dashboard.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#39]
1. Launch the application -> Click on 'My Accounts'
2. Click on 'Organization Admin Login' ->Sign in with gmail id

Issue - Notice that profile pic is displayed very large. Please see the below screenshot.
![image](https://user-images.githubusercontent.com/37771328/38186283-d2edef74-366f-11e8-874d-b88fbfe31a0c.png)

It is showing correctly for Trainer login.

**Comment by samurailens** [comment]
Fixed and Pushed.

Appears in Build : APR 2, 2018
