### ISSUE TITLE
In chat Window enter keyword is not working.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#4]
1. Login as Trainer 
2. Click on any chat conversation 
3. Enter any message, press enter keyword

Notice that when user press enter keyword, entered text is not sending.

Expected Result: When user press enter keyword, the message should be delivered.

Check the screenshot.
![chat window](https://user-images.githubusercontent.com/37771328/37943327-c01b3fc6-3194-11e8-8eb1-1d714f8a3d7b.jpg)

**Comment by gvsphani** [comment]
@NareshTeed will assign this to the appropriate team members to take a look at. 
We will get back to you as early as possible. 

Thanks,
Phani Gardas
