### ISSUE TITLE
Documents - Unable to download the files by clicking on arrow symbol in Manage Documents screen.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#40]
1. Login as Trainer
2. Click on Documents
3. Attach one image and document, after successful uploading.
4. Click on Arrow symbol

![image](https://user-images.githubusercontent.com/37771328/38304643-bf5fb168-3827-11e8-8796-137a97a38548.png)

Issue - When user clicks on Arrow symbol, attachments are not downloading.
Issue - When user hover on arrow symbol, mouse pointer is not changing to hand icon.

Expected Result: If user clicks on arrow icon, attachments should download and should get link. Only for images url is showing. For documents also it should show the link.
- When user hover on arrow symbol, mouse pointer should change to hand icon.

**Comment by gvsphani** [comment]
It is a duplicate, there is a similar issue which was there on #41. Both the issues have got addressed in this build.

![image](https://user-images.githubusercontent.com/19274860/38842738-3f32d2d4-41b1-11e8-8bbb-a7d3f3471929.png)
![image](https://user-images.githubusercontent.com/19274860/38842781-670357ca-41b1-11e8-881b-2329525691e4.png)



Thanks,
Phani

**Comment by gvsphani** [comment]
Issue is fixed in the build v0.1.6
