### ISSUE TITLE
Documents:  User is able to download the documents by clicking on text.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#41]
1. Login as Trainer
2. Click on Documents
3. Attach one image and document, after successful uploading.
4. Click on any text on any line
![image](https://user-images.githubusercontent.com/37771328/38305529-c876aee8-382a-11e8-899f-31d61cff2f64.png)

Issue - User is able to download the documents by clicking on text.

Expected Result: Application should not allow the user to download the attachments if he/she clicks on text. It should allow only when user clicks on Arrow symbol.

**Comment by gvsphani** [comment]
![image](https://user-images.githubusercontent.com/19274860/38842567-57d38a5a-41b0-11e8-8420-628be9caee55.png)

We can download/view the document with the options available beside the name of the document. 

Thanks,
Phani

**Comment by gvsphani** [comment]
Issue is fixed in the build v0.1.6

**Comment by NareshTeed** [comment]
Retested the issue and working fine. Hence changing the status to Closed.

Build no - 0.1.8
