### ISSUE TITLE
Documents -  Spelling mistake for main header.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#42]
1. Login as Trainer
2. Click on Documents

![image](https://user-images.githubusercontent.com/37771328/38306103-0ad36234-382d-11e8-9068-f29bda556a02.png)

**Comment by gvsphani** [comment]
The grammatical error is fixed as seen in the screenshot. 

Thanks,
Phani 

![image](https://user-images.githubusercontent.com/19274860/38842547-3df3053e-41b0-11e8-835c-812c7426fc98.png)

**Comment by gvsphani** [comment]
Issue is fixed in the build v0.1.6

**Comment by NareshTeed** [comment]
Retested the issue and working fine. Hence changing the status to Closed.

Build no - 0.1.8
