### ISSUE TITLE
Assignments - Spelling mistake for Button label and header.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#43]
1. Login as Trainer
2. Click on My Courses / Programs
Verify the button label
![image](https://user-images.githubusercontent.com/37771328/38309541-f3c94954-3837-11e8-914f-cfe8744ca2a3.png)

3. Hover on New Assignment button
Issue - Mouse pointer is not changing to hand icon.
![image](https://user-images.githubusercontent.com/37771328/38309642-26ed0f5a-3838-11e8-92bb-0da2a0093090.png)

4. Click on New Assignment button 
Verify the header name
![image](https://user-images.githubusercontent.com/37771328/38309697-4120b66a-3838-11e8-8efc-131eddb6bc0c.png)

5. Navigate to Dashboard
6. Click on Programs -> In overview tab there are few spelling mistakes. Check the below screenshots:
![image](https://user-images.githubusercontent.com/37771328/38452907-e115c97e-3a6a-11e8-8c1c-f2bbf998cfa3.png)

**Comment by gvsphani** [comment]
It is fixed and the assignment is spelled correctly. Please find the screenshots for the same.

Thanks,
Phani 

![image](https://user-images.githubusercontent.com/19274860/38842268-ad383e66-41ae-11e8-8686-bdc434ebf21c.png)
![image](https://user-images.githubusercontent.com/19274860/38842281-b69b2202-41ae-11e8-92b3-f32839240f19.png)
![image](https://user-images.githubusercontent.com/19274860/38842302-d1f66926-41ae-11e8-91ec-ccf8248d0acd.png)

**Comment by gvsphani** [comment]
Issue is fixed in build v0.1.6

**Comment by NareshTeed** [comment]
Retested the bug and it is reproducible in Programs:
![image](https://user-images.githubusercontent.com/37771328/39163469-3ffacb80-4798-11e8-9951-8674cd5dce94.png)
![image](https://user-images.githubusercontent.com/37771328/39163490-5d01668a-4798-11e8-8de0-d4c879a454cb.png)

Build no - 0.1.8

**Comment by samurailens** [comment]
Programs: Issue reproducible in Programmes tab, although code available. Check for cache issues.

**Comment by NareshTeed** [comment]
Retested the bug and it is reproducible. Check the below screenshot:
![image](https://user-images.githubusercontent.com/37771328/39540839-82eaac10-4e61-11e8-865a-4d0e81c59791.png)
