### ISSUE TITLE
Courses/ programs - When user Clicks on Assignment/Create Batch, it is not navigating to particular tab.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#45]
1. Login as Trainer
2. Click on My Courses / Programs
3. Click on Create Batch / Assignment
![image](https://user-images.githubusercontent.com/37771328/38329235-d8fad812-386a-11e8-8da8-ce4292d182f8.png)
Issue - User is navigating to overview tab instead of Batches / Assignment tab.
Expected Result: 1. If user clicks on Course content (check the below screenshot ), then it should navigate to Overview tab.

![image](https://user-images.githubusercontent.com/37771328/38329478-8feae8a0-386b-11e8-8df7-849500744970.png)

                           2. If user clicks on Create Batch or Assignment, then it should navigate to Particular tab.

This issue is applicable to Programs screen also.

**Comment by gvsphani** [comment]
It is fixed and is working as expected. 
Please check and let us know if you find any issues. 

![image](https://user-images.githubusercontent.com/19274860/38842095-78083f44-41ad-11e8-858d-8e96a59aabeb.png)

![image](https://user-images.githubusercontent.com/19274860/38842097-7dc3617a-41ad-11e8-98af-df0825f73166.png)

Thanks,
Phani

**Comment by gvsphani** [comment]
issue fixed in build v0.1.6

**Comment by NareshTeed** [comment]
Retested the issue and working fine. Hence changing the status to Closed.

Build no - 0.1.8
