### ISSUE TITLE
Students - Spelling mistakes in notifications.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#47]
1. Login as Trainer
2. Click on Students
3. Click on Invite
4. Text invalid text and click on Send Email button

Issue 1 - Invite text is wrong. Please see the below screenshot:
![image](https://user-images.githubusercontent.com/37771328/38331886-2bc7b090-3872-11e8-8ed1-892117528f37.png)
Expected Result: Text should be "Sending Invite to Naresh098@hotmail.com...."
Issue 2 - Successful spelling is wrong check the below screenshot:
![image](https://user-images.githubusercontent.com/37771328/38332176-f76c4152-3872-11e8-8ced-500c52178133.png)

**Comment by samurailens** [comment]
Will appear in Today's build.

**Comment by gvsphani** [comment]
It is working as expected, please try now. 

![image](https://user-images.githubusercontent.com/19274860/38841621-e5f2ef84-41aa-11e8-93a8-1d63c1c710c9.png)


![image](https://user-images.githubusercontent.com/19274860/38841606-dafaa04a-41aa-11e8-88f5-81c4aa5712a5.png)

Thanks,
Phani

**Comment by gvsphani** [comment]
@samurailens Sachin I think there needs to be a space after to and the email. We can ignore it for now as it doesn't affect the information shown on screen. Please take a note for the future enhancements.

**Comment by NareshTeed** [comment]
Retested the issue and working fine. Hence changing the status to Closed.

Build no - 0.1.8
