### ISSUE TITLE
Notices - When user clicks on Publish button, it is navigating to Dashboard instead of previous screen

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#48]
1. Login as Trainer
2. Click on Notices
3. Click on Publish Notice 
4. Enter all details and click on Publish

Notice that when user clicks on Publish button, it is navigating to Dashboard instead of previous screen.

It should navigate to below screen::::
![image](https://user-images.githubusercontent.com/37771328/38333028-051952de-3875-11e8-89d5-8769827f1715.png)

**Comment by gvsphani** [comment]
![image](https://user-images.githubusercontent.com/19274860/38841472-2e9aef80-41aa-11e8-8a68-17d627fbb315.png)

It is working as expected. 

Thanks,
Phani
