### ISSUE TITLE
Trainer - Messages are not delivering to students through chat conversations.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#50]
1. Login as Trainer
2. Create Batch and add one student.
3. Enroll the student 
4. Send a message in batch conversation
5. Login with student

Notice that student is not any message in his dashboard. And also he/she doesn't have option to send a message to trainer.

**Comment by gvsphani** [comment]
@samurailens Sachin please take a look at this. Still see the issue. 

Thanks,
Phani
