### ISSUE TITLE
Chat - Course name is not fully displayed.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#51]
1. Login as Trainer
Check the below screenshot:

![image](https://user-images.githubusercontent.com/37771328/38406475-b94051b8-3992-11e8-9c77-42c5645f61b6.png)

Expected result: Instead of showing half course name, it would be good if we display 
"Web Hacking and ...." and also if user hover on name, it should display the tooltip.

**Comment by gvsphani** [comment]
@gangwork Still see this Gangadhar, please check and see whats going on. 

![image](https://user-images.githubusercontent.com/19274860/38840915-69025d5a-41a7-11e8-91a8-6389dfa4965f.png)


Thanks,
Phani

**Comment by gangwork** [comment]
if its 30 characters long they wanted only to see 10 character n on hover we see full name

**Comment by NareshTeed** [comment]
Instead of leaving space, we can cover till end of the page, please check the below screenshot:
![image](https://user-images.githubusercontent.com/37771328/39162782-ccd68c46-4794-11e8-8d7d-e72b03b4cae9.png)
