### ISSUE TITLE
My Courses - In student tab there is no Invite for new Students.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#52]
1. Login as Trainer 
2. Click on My Courses ->Click on Course details
3. Click on Batch tab
4. For any created batch, click on 'Add Candidate to this Batch'
5. Select batch and navigate to Add student tab

When we are adding new student to the batch at the same time we should have option to send out an Invite (through email and message) to join this course.

![image](https://user-images.githubusercontent.com/37771328/38407082-b94c37dc-3995-11e8-8f74-949cadb755bb.png)

**Comment by samurailens** [comment]
Will appear in Today's build.

**Comment by gvsphani** [comment]
![image](https://user-images.githubusercontent.com/19274860/38840760-d3de45cc-41a6-11e8-97b6-49b02848734d.png)

It has been added to right most as an addition.
Thanks, 
Phani

**Comment by gvsphani** [comment]
issue fixed in build v0.1.6

**Comment by NareshTeed** [comment]
Retested the bug and able to see the Invite tab in Batches. After sending Invite to users, we found few issues: Below are the details:
Check the email ID :
![image](https://user-images.githubusercontent.com/37771328/39141454-8373fc4a-4745-11e8-8d37-6788a8f8e3fa.png)

Click on url:
Sign in with Google, after log into application. User name is not displaying.
![image](https://user-images.githubusercontent.com/37771328/39142333-0065abc0-4748-11e8-8e70-b036f6cefa56.png)

**Comment by samurailens** [comment]
The issue raised is fixed as of now.

The invite email shall contain fixes for 'Login via Invitation' scenarios.
