### ISSUE TITLE
My Courses - When user clicks on View Candidate list, application is not showing any candidate list.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#53]
1. Login as a Trainer
2. Click on My Courses ->Click on Course contents
3. For any created batch, Click on View Candidate list

Notice that when user clicks on View Candidate list, candidate list is not showing.

![image](https://user-images.githubusercontent.com/37771328/38409129-d35120b8-399d-11e8-8ec6-32eba0c6d43e.png)

**Comment by gvsphani** [comment]
![image](https://user-images.githubusercontent.com/19274860/38840675-748e8a00-41a6-11e8-9a14-bc6dcd60e2a7.png)

It is working as expected. Please let us know if you find any issues. 

Thanks,
Phani

**Comment by gvsphani** [comment]
issue fixed in build v0.1.6

**Comment by NareshTeed** [comment]
Retested the issue and working fine. Hence changing the status to Closed.

Build no - 0.1.8
