### ISSUE TITLE
My Courses - Batch - User doesn't have option to write Batch Name.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#55]
1. Login as a Trainer
2. Click on My courses - >Click on Course contents
3. Click on Batches tab
4. Click on New Batch

Notice that User doesn't have option to enter Batch name.

Expected Result: User should have option to write the Batch name. So that they can name it as Morning Batch and Evening Batch.

**Comment by samurailens** [comment]
Shall close this with this as last addition to batch.  No more additional details shall be added to this. 

Adding new details will impact Database design, Mobile Applications for Trainer/Orgs and Students. Even though it appears minor detail, the changes have to be carried out in 2 Mobile Apps for 3 Different User roles, which in itself will involve a lot of development activity. 

Any new additions post this closure shall be taken as enhancements.

**Comment by samurailens** [comment]
@NareshTeed : Check it up for final closure.

**Comment by gvsphani** [comment]
It is working fine now. 


![image](https://user-images.githubusercontent.com/19274860/38840386-f0ae47e4-41a4-11e8-8b13-0e056d51ebce.png)

![image](https://user-images.githubusercontent.com/19274860/38840427-32543ab4-41a5-11e8-99e5-5ccdc9f88b96.png)


There is a new field appearing where the user can mention the name of the batch and the timings. 

Thanks,
Phani

**Comment by NareshTeed** [comment]
Retested the issue and working fine. Hence changing the status to Closed.

Build no - 0.1.8
