### ISSUE TITLE
Landing page - Course description should show as short.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#63]
1. Launch the Teedknow.com
check the below screenshot:

Full description is showing, if user is having more than 10 lines then it will cover full screen.

Expected Result: Only few lines should be displayed and remaining should be shown as '.......' 
Example - The Oracle E - Business  suite is a complete set of business applications that enables .........

**Comment by samurailens** [comment]
Closing this issue as now onwards course description is limited to 100 characters.
