### ISSUE TITLE
Chat - If user press enter in typing area, empty message is going in chat window.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#69]
1. Login as Trainer
2. Click on any chat conversation
3. Place the cursor in typing area
4. Press Enter keyword in keyboard

Notice that empty message is delivering in Chat window. Please check the below screenshot:

![image](https://user-images.githubusercontent.com/37771328/38465088-5ba2f50c-3b35-11e8-940e-d71b1168dcdb.png)

Expected Result: Without typing any message if user press Enter keyword, empty message should not be delivered.

**Comment by samurailens** [comment]
Empty messages cannot be sent anymore. Issue is fixed

Fix Appears in the build : 09-04-2018

**Comment by NareshTeed** [comment]
Retested the issue and working fine. Hence changing the status to Closed.

Build no - 0.1.8
