### ISSUE TITLE
Trainer - End user doesn't know whether Author profile able to see or not.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#70]
1. Login as Trainer
2. Navigate to main page
3. Click on any course
4. Hover on Author name
![image](https://user-images.githubusercontent.com/37771328/38469076-8ea9bc7e-3b6c-11e8-8a0b-0350ba5d94be.png)
Expected Result : When user hover on author name, it should display the hand icon and also it should show some indication that Author is having profile information.

**Comment by samurailens** [comment]
Tool tips added and cursor pointer changed.

Will appear in the build : 9-04-2018

**Comment by NareshTeed** [comment]
Retested the issue and working fine. Hence changing the status to Closed.

Build no - 0.1.8
