### ISSUE TITLE
Courses - Extra labels are displayed.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#74]
1. Login as Organizer 
2. Click on Courses -> Click on New course
3. Click on ''See an example of a course''
![image](https://user-images.githubusercontent.com/37771328/38766480-697c6e00-3ff0-11e8-99c3-5b9f696cb832.png)
Check the below screenshot for issue:
![image](https://user-images.githubusercontent.com/37771328/38766483-7da156d4-3ff0-11e8-8d9c-9a6509ce3887.png)
Notice that in above screenshot, My account and Partner with Teedknow are displayed. 

Is this expected behavior because generally it will display in landing page when user launches the application at that time it will be seen.

**Comment by samurailens** [comment]
Auth does not logout completely

**Comment by NareshTeed** [comment]
[cid:13485f7e-127f-4277-9fdd-d5442a9f6789]

________________________________
