### ISSUE TITLE
Alignment is not right for Courses tiles in landing page.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#76]
![image](https://user-images.githubusercontent.com/37771328/38766866-f87778ac-3ff5-11e8-887b-40fedc36c45b.png)

**Comment by NareshTeed** [comment]
Retested the bug and it is failing at featured courses at Hyderabad. 

Check the below screenshot:
![image](https://user-images.githubusercontent.com/37771328/39085636-34955f4a-45a3-11e8-8bc4-33da107c3895.png)

**Comment by NareshTeed** [comment]
Retested the bug and still it is failing, please check the below screenshots:

![image](https://user-images.githubusercontent.com/37771328/39524665-45f73f3c-4e37-11e8-8d31-821a1aa3c968.png)

![image](https://user-images.githubusercontent.com/37771328/39524734-8f74cdc8-4e37-11e8-82fe-a0267ad2ed4d.png)

**Comment by samurailens** [comment]
Shall not be fixed as this is not an issue with respect to the application.

It's more dependent on content generated by the application. 

Shall be taken up on lower priority.
