### ISSUE TITLE
Assignment details are missing after clicking on Edit icon.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#8]
1. Login as Trainer
2. Click on Dashboard
3. Click on My Courses -> Click on Assignment
4. Click on Edit icon
5. Click on View button

Notice that when user clicks on View button, Assignment details are not displaying.

Expected Result: When user clicks on View button, Assignment details should be displayed.

![image](https://user-images.githubusercontent.com/37771328/37945402-ae432990-319d-11e8-8f0d-847ba591f4e8.png)

**Comment by samurailens** [comment]
Assignments cannot be edited since we are letting them submit documents as assignments. Editing uploaded document is beyond scope of the project. 

We have adjusted this UI and pushed it. Shall appear in new build.

Appears in Build : APR 2, 2018
