### ISSUE TITLE
After creating Course/Batch, Chat conversation is not created in Conversation window.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#80]
1. Launch the Teedknow.com
2. Login as Organizer
3. Create Course and Batch 

Notice that after creating course and batch, Chat conversation is not created in Conversation window.

Please see the below screenshot:

![image](https://user-images.githubusercontent.com/37771328/38775919-76898a2c-40ab-11e8-9474-1af4635764f0.png)

**Comment by NareshTeed** [comment]
Retested the bug and Chat conversation is created only for Course. Chat conversation is not creating for Batches. Build no - 0.1.8
For Trainer it is working fine. Please check it.

**Comment by NareshTeed** [comment]
Retested the bug and Chat conversation is created only for Course. Chat conversation is not creating for Batches. Build no - 0.1.10
For Trainer it is working fine. Please check it.

**Comment by samurailens** [comment]
Retested for Organization and works fine. Could not reproduce  the issue.

Freshly created a course and program, the chat conversations were instantly created. 

<img width="1418" alt="screen shot 2018-05-02 at 11 35 59 pm" src="https://user-images.githubusercontent.com/5208310/39540968-ef4e42a4-4e61-11e8-9e8c-75cee035c74b.png">

Also, the corresponding batches are also created. 

<img width="329" alt="screen shot 2018-05-03 at 12 34 44 am" src="https://user-images.githubusercontent.com/5208310/39543793-ce033160-4e69-11e8-9cea-54bec690044a.png">

The issue might be with old account data mismatch. No fixes need for new registrations.
