### ISSUE TITLE
Chat - If user has more than 18 Conversations then remaining conversations are not visible.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#83]
1. Launch the Teedknow.
2. Login as a Trainer
Check the below screenshot for issue:

![image](https://user-images.githubusercontent.com/37771328/38778138-08eb3f3e-40d2-11e8-89ce-2de7553ab3c2.png)

In above screenshot, user has more than 20 conversations in his list he is able to view only 17 conversations. 
Workaround - If user decrease the zoom, then he is able to view the all list.

Expected Result: It would be good if user has vertical scroll bar.

2. Another issue:

![image](https://user-images.githubusercontent.com/37771328/38778154-679071bc-40d2-11e8-9437-868e8b4ce24f.png)

Names should reach corner of the page, from there application should display like this .....

or else It would be good if user has permission to drag the panel.

**Comment by NareshTeed** [comment]
Retested the bug and first scenario is passing. Second scenario still able to replicate.

Build no - 0.1.8

**Comment by NareshTeed** [comment]
Retested the bug and Names should reach corner of the page, from there application should display like this .....
![image](https://user-images.githubusercontent.com/37771328/39526688-2dcf8efe-4e3d-11e8-9fc9-f9b33b56377d.png)

**Comment by samurailens** [comment]
Please check again.
