### ISSUE TITLE
Student - Alignment is disturbed. 

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#86]
1. Login as a Student
2. Navigate to Chat conversations and scroll down 

Check the below screenshot
for issue:

![image](https://user-images.githubusercontent.com/37771328/39085386-233e958a-459f-11e8-8f15-f724bcaa5549.png)

**Comment by kranthi91** [comment]
![image](https://user-images.githubusercontent.com/24225228/39128129-99fe4d42-4724-11e8-9729-bd3007462952.png)

Alignment is good now.

**Comment by NareshTeed** [comment]
Retested the issue and working fine. Hence changing the status to Closed.

Build no - 0.1.8
