### ISSUE TITLE
Search field is not working as expected.

### ISSUE THREAD

**Issue by NareshTeed** [samurailens/teedknow-issue-tracker#88]
1. Launch the Teedknow.com
2. Enter any course like Guitar
Result: It will show all courses related to Guitar. 
3. Click on Search icon

Notice that when user clicks on Search icon, all Guitar courses are not displaying in page.

For reference check the below screenshots:
![image](https://user-images.githubusercontent.com/37771328/39085658-92629660-45a3-11e8-8a2c-7cd1d14a934e.png)

If user clicks on Search icon then it will show all courses like below screenshot:
![image](https://user-images.githubusercontent.com/37771328/39085720-7fd7e5da-45a4-11e8-8d25-fd8821b29f74.png)

**Comment by samurailens** [comment]
New search screen is now live
